swagger: '2.0'
info:
    version: '1.0.0'
    title: 'myApp'
host: localhost:3002
basePath: /
schemes:
    - http
consumes:
    - application/json
produces:
    - application/json
paths:
    /api/login:
        post:
            tags: 'login'
            summary: This should create a new ice cream.
            description: login in to aplication.
            consumes: — application/json
            parameters:
                — login: string
                — password: string 
            schema:
                type: object
                properties:
                    flavor:
                    type: string
            responses:
                200:
                    description: Receive back JWT token.
